CREATE TABLE tickets(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    detail_message VARCHAR(100),
    stacktrace CLOB,
    ticket_class_id INT NOT NULL DEFAULT 13,
    PRIMARY KEY (id)
);

CREATE TABLE ticket_occurrences(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    occurrence_timestamp TIMESTAMP NOT NULL,
    ticket_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);